/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author fernandomanuel
 */
public class MensajeGuardado extends javax.swing.JPanel {

    /**
     * Creates new form ActividadGuardada
     */
    public MensajeGuardado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MensajeBorrado = new javax.swing.JPanel();
        jBotonAceptar = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();

        MensajeBorrado.setBackground(new java.awt.Color(0, 153, 204));

        jBotonAceptar.setBackground(new java.awt.Color(0, 153, 0));
        jBotonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonAceptar.setText("Aceptar");
        jBotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAceptarActionPerformed(evt);
            }
        });

        jLabelMensaje.setText("Su Actividad Ha Sido Guardada");

        javax.swing.GroupLayout MensajeBorradoLayout = new javax.swing.GroupLayout(MensajeBorrado);
        MensajeBorrado.setLayout(MensajeBorradoLayout);
        MensajeBorradoLayout.setHorizontalGroup(
            MensajeBorradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeBorradoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(MensajeBorradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBotonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        MensajeBorradoLayout.setVerticalGroup(
            MensajeBorradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeBorradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensaje)
                .addGap(18, 18, 18)
                .addComponent(jBotonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MensajeBorrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MensajeBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAceptarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBotonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MensajeBorrado;
    private javax.swing.JButton jBotonAceptar;
    private javax.swing.JLabel jLabelMensaje;
    // End of variables declaration//GEN-END:variables
}
